dist: bionic

env:
  global:
    - PREFIX=pkskubeflow
    - REGISTRY="docker.io"
    - TAG=v0.9.0
    - VERSION=v1beta1

arch:
  - arm64

services:
  - docker

before_install:
  - git clone -b ${TAG} --depth 1 https://github.com/kubeflow/katib.git

script:
  - cd katib/scripts/${VERSION}
  - ./build.sh -t ${TAG} -r ${REGISTRY} -p ${PREFIX}
  - docker login -u ${DOCKER_USER} -p ${DOCKER_PWD}
  - docker push ${REGISTRY}/${PREFIX}/katib-controller:${TAG}
  - docker push ${REGISTRY}/${PREFIX}/katib-db-manager:${TAG}
  - docker push ${REGISTRY}/${PREFIX}/katib-ui:${TAG}
  - docker push ${REGISTRY}/${PREFIX}/file-metrics-collector:${TAG}
  - docker push ${REGISTRY}/${PREFIX}/tfevent-metrics-collector:${TAG}
  - docker push ${REGISTRY}/${PREFIX}/suggestion-hyperopt:${TAG}
  - docker push ${REGISTRY}/${PREFIX}/suggestion-skopt:${TAG}
  - docker push ${REGISTRY}/${PREFIX}/suggestion-chocolate:${TAG}
  - docker push ${REGISTRY}/${PREFIX}/suggestion-enas:${TAG}
  - docker push ${REGISTRY}/${PREFIX}/suggestion-hyperband:${TAG}
  - docker push ${REGISTRY}/${PREFIX}/suggestion-goptuna:${TAG}
#  - docker push ${REGISTRY}/${PREFIX}/suggestion-darts:${TAG}
